### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sonu-singh22** [SuperiorExtended/official_devices#11]
### Device you want to apply for

Redmi Note 4 & 4x (Mido)

### Device Tree Sources

https://github.com/sonu-singh22/device_xiaomi_mido/tree/supex-14
https://github.com/sonu-singh22/vendor_xiaomi_mido
https://github.com/sonu-singh22/kernel_xiaomi_mido

### Number of ROM's you maintain officially/unofficially, also name them

3 Afterlife, Cherish, Spark

### Any Exceptions/special concern?

Need little guidance and assistance from you pro devs !

### Telegram username

https://t.me/RpSiNgH_22

### GitHub username

https://github.com/sonu-singh22

**Comment by Darkstar085** [comment]
Approved..!!!
