### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aniketghodake10** [SuperiorExtended/official_devices#14]
### Device you want to apply for

Realme X2 Pro (samurai)

### Device Tree Sources

https://github.com/aniketghodake10/android_device_realme_samurai/tree/superiora14
https://github.com/aniketghodake10/android_kernel_realme_sm8150/tree/lineage-21
https://github.com/aniketghodake10/proprietary_vendor_realme_samurai/tree/lineage-21
https://github.com/aniketghodake10/android_packages_apps_RealmeParts/tree/lineage-21

### Number of ROM's you maintain officially/unofficially, also name them

ArrowOS (Redmi note 5 vince)

### Any Exceptions/special concern?

No.

### Telegram username

Niklaus45

### GitHub username

aniketghodake10

**Comment by athizz2005** [comment]
rebase and own a dt dont just take someone else dt compile a rom and apply for official
