### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jignesh2023** [SuperiorExtended/official_devices#15]
### Device you want to apply for

Group for Redmi Note 11T / 11S 5G/ POCO M4 Pro 5G (evergo/opal/evergreen)

### Device Tree Sources

> https://github.com/jignesh2023/device_xiaomi_everpal/tree/fourteen

> https://github.com/jignesh2023/device_xiaomi_mt6833-common/tree/fourteen

### Number of ROM's you maintain officially/unofficially, also name them

All rom are unofficial > spark, afterlife, cherish, skyline 

### Any Exceptions/special concern?

> xiaomi kernel source is fuxed that's why we use pre built kernel 

> we recently moved to common tree that's why we don't make selinux enforce 

### Telegram username

@Jignesh2023

### GitHub username

https://github.com/jignesh2023

**Comment by jignesh2023** [comment]
Any specific reason?

**Comment by athizz2005** [comment]
just a bringup commit over someone else dt?

**Comment by jignesh2023** [comment]
We are a community just moved to new common device tree that's why u only
see bringing commits
