### ISSUE TITLE
Applying 

### ISSUE THREAD

**Issue by Fizzyapps** [SuperiorExtended/official_devices#16]
### Device you want to apply for

Pixel 8 pro (husky)

### Device Tree Sources

https://android.googlesource.com/device/google/shusky-kernel/

https://github.com/Fizzyapps/device_google_shusky

https://github.com/Fizzyapps/android_vendor_superior

### Number of ROM's you maintain officially/unofficially, also name them

1 superior extended unofficial 

### Any Exceptions/special concern?

This a awesome rom an I would love to continue bringing it to the husky 

### Telegram username

@Fizzyapps

### GitHub username

https://github.com/Fizzyapps

**Comment by athizz2005** [comment]
pls use ur dt dont just use someone else's DT and just do a bringup commit and apply for official...pls show in efforts and some basic git knowledge in rebasing the DT or cherry-piccking commits with giving proper authorship...
